#include <stdio.h>
#include <stdlib.h>
#include <string.h>

const char round1[] = "ACCBACBCCCCBBCACCCCCAACBCCCABBCAAACCAABCBABAACBBCCAACAACBAABCCBBAAACCCABBCAAACCCCCCBACCAABBCCCABABAAAABBCAABBCAACACCACCCCCCBABBAACCACCBCBBCCBBAABAACCCACCCBBBBBABBACCABCCBBABBABBBBBBBCCBACACBBABACBCBBABAAAABAAABCACAAABBABCBACCCBBBCCBCCBABAABCACBBBABCACCCACBCABBABCCCACBCBBCABCBCACCCABCBBCCAABBABCCBBAAACBCACBABABBCBABBCBACACABBCCCBCCBCCCBABBBCCBABBCCCCAACBABCBAACACBABCAAABAABBCCBCBCCBACACCCBCACBBAAAAAACACAAACCCABBCBCCCACBABBCBABBCACBBABCACBAABBBABBCCAACCAABBCCABCBBACAACCBACAAABCBBACCCBBBCCCAAABABBBCCCABBBBBBCCAACACAACCAACCCABAAABCCAABCCCBBBBCCBABCCBBBCBBABCBAAACACCACAAACBCCCABACACCCCABCABACCACBBCACABCCABBABAACBBCABBAABBCAACBCCACAABABAAABCCBBBCAAABCCBBBAACCBCBAACBAABCACACBBBBCBBABCBBCBCCABBBCCCBCACAACABCABABBBABCCCBCBCACCABAACBCACCAAACBBBACCBCCCBBCABBBABACACABAABCBAABABBACBCACCCBACCBBBACAACBABCBCACACCBBACBABCACAABBCBBAABBABAABCCACAAACBCBBCCBCBBABABABCCCBACCCCBACACBCAABBAACCBBCCCCCCBAACACACBCACACCBACAACCBCBBABCBBACACACAABBAABBBCBCBCBCCBBCCAAACBBCABCCBACABCACBCCCCBBAAAACBAAAABCAACCAABCCAACBB";
const char round2[] = "BCCADBDAADADxADABADDDCCAABABDxCACCAADBCDBDCCxADCCxCBABDBDABCDDxDACDCABBBACADCDDCACADxxxACCAACCDBxBAxAxCCDDBABBBBACxDDBxABxCCBDBCBCAxCABAxCxDBxxBDCCAAABACxxDCDABxADDBBABAxCBCBBxABDDxDBCDBCBBBADCCxDABBCxADCBDCDBBDxACxDABCABBCACxCBBxBCADBBABDDDBDDBCDCDBDxDDCDABBxCxCBBDCBDDBDCDCxBCBBDDDxxAxDAxBCxBBCDCDBADxxBCxBBDAACxCACAxBBCxBBBABCAACCxBDADDxCBCxxCBDBABCCBDCDBDADACxBBBBDCCDCxABBBABCAxCDxBDDADCBACxBAACADBCCDDCDDDCxAxDxCxADDCxABDCCxDBCBBCCDCBBxDAAxABACDBxDDBCBABBAxBCBCDxCAABDBCCCxCCADAACBADCACCBDCBBADxDCDBCxxBDACCCBCACCxBAxDDACACCDACBCACCCDABxAAACABCDDADCBDBCDADDCCAAxCCADCAAAABABCAAAADxAACCCBDDBxBCBDADBCCADADDAxDCDBCACCABACBABCCDADBCDCACBxBCDxACCBDDBAACBAAABDBxCAACBADACCDCADCBxDABCDBBCCBADBADDDDxCABDBBBDBDACDAAABDBAACABCAAACCCxDAxDDCCABBAACDBAAADCADBACxxCBCAADCCBBCCACAABBDCCDBxCDCCDACBCBxDDCADCDBACACADBBCAAxDBABCCxxDCBDBABCxBBDBACDAABCCBxDxACAxCBDDACCCAAABCCDxDDxCBxCCBBBCADADBDBCDACCDxDDBABACxCBDABBBDCBBxACBCCDBCBxBBBABAABBCCBDBDBCDAxACBBAxDxxBBDCBCAAAADACCABDxACxDADDBBDAABCCACDxCADDAxDDACDCDDCDCCABBBDCDADBBADBDADCBCBDDCDxCDCDCABCBxxxxACBBxDACCxxCADxABABAAxCCAxBABBBAADBADACDBDADBDABCDxxCAxBDDBACCCCDDxABDBCCCACABBDDCCABBCACBABCCBACDxDAAAAACAAADDADxBBDxBCABAABACCCBCBACAAxDBDCDAAAxADBDAABBAxABxCAADBAxABBBAxDxBxBBCCBCCDxCDDBABBADAACBDCBABDADxCAxDAxDBBCCxDBDCDCAxCDxACBBADBxCBABABBxCADAADBDABxBDDDBAxBBBxDBxABxADCDCxDCAxAxDADAAADCDBBxACCBCDBCxBBDBDDDBBDBDCDCCCDCDACDxxBxxBAxxDABCDBDDxABxDCCAxCACCCCDBCCACBCxCABDACBxDxCDCDDBBDBCDAxADAxDDCCAACAAxACBCDABxBCBADCCxBDxDDCCBAACCBxBCABCBBBBAADCAADCDACDBBABBAxBxAADDCBABxBBDADABBBBBCCBBBCCAADABCBDCCCCAABxBAACBDxBxBCxCADCCACxBABxCxACCACACACDDBCDCxBCBDCADCBACCBBxCBxDDCCxACCBADBAxADCDDADCBCDDDBxCCDAAxBDBBDBADAADCCCBDBxBCCBDDxCCADADDAAABCxBBCBBABxBCDBCCCDxBDxCBDBDxDAxCCCBBBxAAxDBDAAxADBCBDBAABAABBDACABxxCCCCCBBAxACABCADBADCCABAxADBCCABDDBCDCAAAABCBBBBCAxDAxACCCxADBCCCCBABxBDDCADBxDCDBCCDCDCACCDDDxAADCxDCBDACCBCBDCCBDAAACBBCABxAABABDACACBBDABACBDxCABDDCADCADCDBCADDDCxACCxBBCDxDCCBDABCBBxDACAAAAAABxBCBDCCBBBDDCCBDDCDDBDBBCBCDDBADAAAAxABDACxDCBCDC";

int get_potions(char monster) {
    switch(monster) {
        case 'B': return 1;
        case 'C': return 3;
        case 'D': return 5;
        default: return 0;
    }
}

int main() {

    size_t potions = 0;

    for (size_t i = 0; i < strlen(round1); ++i) {
        potions += get_potions(round1[i]);
    }

    printf("Round 1 potions: %zu\n", potions);

    // round 2
    potions = 0;

    for (size_t i = 0; i < strlen(round2); i += 2) {
        potions += get_potions(round2[i]);
        potions += get_potions(round2[i + 1]);

        if (round2[i] != 'x' && round2[i + 1] != 'x') {
            potions += 2;
        }
    }

    printf("Round 2 potions: %zu\n", potions);

    return 0;
}